/*
  Auto-generated by Spline
*/
import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/HZajAMeCpzhAS6Ty/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#74757a']} />
      <group {...props} dispose={null}>
        <mesh
          name="tea flying"
          geometry={nodes['tea flying'].geometry}
          material={materials.tea}
          castShadow
          receiveShadow
          position={[-72.31, 1, -42.94]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        />
        <group name="teapot" position={[-637.27, -750.67, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={2.03}>
          <mesh
            name="Cylinder"
            geometry={nodes.Cylinder.geometry}
            material={materials['Cylinder Material']}
            castShadow
            receiveShadow
            position={[-139.05, 175.37, 0]}
            rotation={[0, 0, -2.71]}
            scale={0.79}
          />
          <mesh
            name="handle"
            geometry={nodes.handle.geometry}
            material={materials['handle Material']}
            castShadow
            receiveShadow
            position={[107.38, 169.2, 5.35]}
            rotation={[0, 0, -0.9]}
            scale={0.79}
          />
          <group name="Group" position={[-2.73, 227.84, -1.07]} scale={0.79}>
            <mesh
              name="lid"
              geometry={nodes.lid.geometry}
              material={materials['lid Material']}
              castShadow
              receiveShadow
              position={[1.68, -53.49, 0.94]}
              scale={[0.92, 1, 0.94]}
            />
            <mesh
              name="lid1"
              geometry={nodes.lid1.geometry}
              material={materials['lid1 Material']}
              castShadow
              receiveShadow
              position={[0.08, 23.62, 1.2]}
            />
          </group>
          <mesh
            name="teapot1"
            geometry={nodes.teapot1.geometry}
            material={materials['teapot1 Material']}
            castShadow
            receiveShadow
            position={[-1.4, 117.03, 0]}
            scale={0.79}
          />
        </group>
        <group name="plants" position={[175.28, -1089.74, 8.64]} scale={1.37}>
          <mesh
            name="plant"
            geometry={nodes.plant.geometry}
            material={materials.plant}
            castShadow
            receiveShadow
            position={[93.85, 9.45, -10.65]}
            rotation={[0.14, 0.1, -0.11]}
            scale={0.5}
          />
          <mesh
            name="plant1"
            geometry={nodes.plant1.geometry}
            material={materials.plant}
            castShadow
            receiveShadow
            position={[-117.15, -19.08, -15.82]}
            rotation={[0.24, -1.16, 0.27]}
            scale={0.5}
          />
          <mesh
            name="soil"
            geometry={nodes.soil.geometry}
            material={materials.green}
            castShadow
            receiveShadow
            position={[14.59, -138.68, -4.99]}
            scale={[0.53, 0.53, 0.45]}
          />
        </group>
        <group name="mug" position={[-338.85, -1802.1, 8.64]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.75}>
          <mesh
            name="tea mug"
            geometry={nodes['tea mug'].geometry}
            material={materials.tea}
            castShadow
            receiveShadow
            position={[-61.27, -150.63, 0.26]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.33}
          />
          <mesh
            name="body"
            geometry={nodes.body.geometry}
            material={materials['body Material']}
            castShadow
            receiveShadow
            position={[-61.27, -0.78, 0]}
            scale={3.05}
          />
          <mesh
            name="handle1"
            geometry={nodes.handle1.geometry}
            material={materials['handle1 Material']}
            castShadow
            receiveShadow
            position={[71.29, 62.97, -1.16]}
            scale={[0.15, 0.69, 0.33]}
          />
        </group>
        <pointLight
          name="Point Light"
          castShadow
          intensity={1}
          distance={8205}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={100}
          shadow-camera-far={100000}
          position={[0, -995.52, 4009.37]}
        />
        <OrthographicCamera
          name="1"
          makeDefault={true}
          far={100000}
          near={-100000}
          position={[-251.42, -349.93, 933.35]}
          rotation={[0, 0, 0]}
        />
        <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
      </group>
    </>
  )
}
